name: Bug report
description: File a bug report. ðŸž
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide the details below to help us address the issue.

  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: >-
        We need a detailed description of the issue. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
      placeholder: "Describe the bug in detail, including steps to reproduce, expected behavior, and actual behavior."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Home Assistant Environment
  - type: input
    id: version
    attributes:
      label: What version of the integration has the issue?
      description: >
        Can be found in: [Settings â‡’ Devices &amp; services â‡’ Integrations â‡’ Click on integration name](https://my.home-assistant.io/redirect/integration/?domain=zcsmower).

        [![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=zcsmower)
      placeholder: v1.1.0
    validations:
      required: true
  - type: input
    attributes:
      label: What was the last working version of the integration?
      description: >
        If known, otherwise leave blank.
      placeholder: v1.0.0
  - type: input
    attributes:
      label: What version of Home Assistant Core has the issue?
      description: >
        Can be found in: [Settings â‡’ System â‡’ Repairs â‡’ Three Dots in Upper Right â‡’ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      placeholder: core-2024.9.0
    validations:
      required: true
  - type: input
    attributes:
      label: What was the last working version of Home Assistant Core?
      description: >
        If known, otherwise leave blank.
      placeholder: core-2024.8.0

  - type: markdown
    attributes:
      value: |
        ## Lawn Mower Environment
  - type: input
    attributes:
      label: Which lawn mower model do you own?
      description: >
        In most cases, we need the exact model name of your lawn mower. Even better would be the first six characters of the serial number.
      placeholder: e.g. Ambrogio Twenty Deluxe (AM020D)
    validations:
      required: true
  - type: input
    attributes:
      label: Which firmware is running on your lawn mower?
      description: >
        Can be found after open the lawn mower app on your mobile device: Info â‡’ General â‡’ Version.
      placeholder: "r70475"
  - type: dropdown
    attributes:
      label: Is the Connect Module on your lawn power still valid?
      description: >
        Can be found after open the lawn mower app on your mobile device: Info â‡’ Connect â‡’ Expire date.
      options:
        - "Yes"
        - "No"
  - type: dropdown
    attributes:
      label: Has your lawn mower been recently updated?
      description: >
        If your lawn mower has recently been updated, a bug or breaking change may have been hidden in the latest firmware.
      options:
        - "No"
        - "Yes"

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information 
      description: >-
        The integration provide the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data for the device you are having issues with,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues faster.
      placeholder: "Drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Logs
      description: Anything in the logs that might be useful for us? For example, error message, or stack traces.
      render: txt
      placeholder: "Paste logs"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Screenshots
      description: Any relevant screenshots that can help identify the issue
      placeholder: "Upload screenshots"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below.
    validations:
      required: false
