name: Validate with hassfest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v5"
      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"
